import turtle
a = turtle.Turtle()
a.fillcolor("black")
a.begin_fill()
a.color("orange")
a.up()
a.setpos(-100,50)
a.down()
a.circle(50,steps=5)
a.end_fill()

b = turtle.Turtle()
b.color()
b.begin_fill()
b.up()
b.setpos(50, 50)
b.down()
b.circle(50,steps=10)
b.end_fill()

c = turtle.Turtle()
c.color("violet")
c.begin_fill()
c.up()
c.setpos(-25,-100)
c.down()
c.circle(50,steps=3)
c.end_fill()